# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/ConcordanceTab.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ConcordanceTab(object):
    def setupUi(self, ConcordanceTab):
        ConcordanceTab.setObjectName(_fromUtf8("ConcordanceTab"))
        ConcordanceTab.resize(781, 596)
        ConcordanceTab.setLocale(QtCore.QLocale(QtCore.QLocale.French, QtCore.QLocale.France))
        self.verticalLayout_2 = QtGui.QVBoxLayout(ConcordanceTab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.concordanceSourceGroupBox = QtGui.QGroupBox(ConcordanceTab)
        self.concordanceSourceGroupBox.setObjectName(_fromUtf8("concordanceSourceGroupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.concordanceSourceGroupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.concordanceSourceSelectPushButton = QtGui.QPushButton(self.concordanceSourceGroupBox)
        self.concordanceSourceSelectPushButton.setAutoDefault(False)
        self.concordanceSourceSelectPushButton.setObjectName(_fromUtf8("concordanceSourceSelectPushButton"))
        self.gridLayout_2.addWidget(self.concordanceSourceSelectPushButton, 0, 1, 1, 1)
        self.concordanceSourceLineEdit = QtGui.QLineEdit(self.concordanceSourceGroupBox)
        self.concordanceSourceLineEdit.setObjectName(_fromUtf8("concordanceSourceLineEdit"))
        self.gridLayout_2.addWidget(self.concordanceSourceLineEdit, 0, 0, 1, 1)
        self.concordanceSourceDisplayParametersGroupBox = QtGui.QGroupBox(self.concordanceSourceGroupBox)
        self.concordanceSourceDisplayParametersGroupBox.setObjectName(_fromUtf8("concordanceSourceDisplayParametersGroupBox"))
        self.gridLayout = QtGui.QGridLayout(self.concordanceSourceDisplayParametersGroupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.concordanceSourceWordsAfterLabel = QtGui.QLabel(self.concordanceSourceDisplayParametersGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.concordanceSourceWordsAfterLabel.sizePolicy().hasHeightForWidth())
        self.concordanceSourceWordsAfterLabel.setSizePolicy(sizePolicy)
        self.concordanceSourceWordsAfterLabel.setObjectName(_fromUtf8("concordanceSourceWordsAfterLabel"))
        self.gridLayout.addWidget(self.concordanceSourceWordsAfterLabel, 0, 2, 1, 1)
        self.concordanceSourceWordsBeforeSpinBox = QtGui.QSpinBox(self.concordanceSourceDisplayParametersGroupBox)
        self.concordanceSourceWordsBeforeSpinBox.setMinimum(0)
        self.concordanceSourceWordsBeforeSpinBox.setMaximum(20)
        self.concordanceSourceWordsBeforeSpinBox.setProperty("value", 3)
        self.concordanceSourceWordsBeforeSpinBox.setObjectName(_fromUtf8("concordanceSourceWordsBeforeSpinBox"))
        self.gridLayout.addWidget(self.concordanceSourceWordsBeforeSpinBox, 0, 1, 1, 1)
        self.concordanceSourceWordsBeforeLabel = QtGui.QLabel(self.concordanceSourceDisplayParametersGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.concordanceSourceWordsBeforeLabel.sizePolicy().hasHeightForWidth())
        self.concordanceSourceWordsBeforeLabel.setSizePolicy(sizePolicy)
        self.concordanceSourceWordsBeforeLabel.setObjectName(_fromUtf8("concordanceSourceWordsBeforeLabel"))
        self.gridLayout.addWidget(self.concordanceSourceWordsBeforeLabel, 0, 0, 1, 1)
        self.concordanceSourceWordsAfterSpinBox = QtGui.QSpinBox(self.concordanceSourceDisplayParametersGroupBox)
        self.concordanceSourceWordsAfterSpinBox.setMinimum(0)
        self.concordanceSourceWordsAfterSpinBox.setMaximum(20)
        self.concordanceSourceWordsAfterSpinBox.setProperty("value", 3)
        self.concordanceSourceWordsAfterSpinBox.setObjectName(_fromUtf8("concordanceSourceWordsAfterSpinBox"))
        self.gridLayout.addWidget(self.concordanceSourceWordsAfterSpinBox, 0, 3, 1, 1)
        self.concordanceSourceFontColorLabel = QtGui.QLabel(self.concordanceSourceDisplayParametersGroupBox)
        self.concordanceSourceFontColorLabel.setObjectName(_fromUtf8("concordanceSourceFontColorLabel"))
        self.gridLayout.addWidget(self.concordanceSourceFontColorLabel, 1, 0, 1, 1)
        self.concordanceSourceBackgroundColorLabel = QtGui.QLabel(self.concordanceSourceDisplayParametersGroupBox)
        self.concordanceSourceBackgroundColorLabel.setObjectName(_fromUtf8("concordanceSourceBackgroundColorLabel"))
        self.gridLayout.addWidget(self.concordanceSourceBackgroundColorLabel, 1, 2, 1, 1)
        self.concordanceSourceFontColorPushButton = QtGui.QPushButton(self.concordanceSourceDisplayParametersGroupBox)
        self.concordanceSourceFontColorPushButton.setObjectName(_fromUtf8("concordanceSourceFontColorPushButton"))
        self.gridLayout.addWidget(self.concordanceSourceFontColorPushButton, 1, 1, 1, 1)
        self.concordanceSourceBackgroundColorPushButton = QtGui.QPushButton(self.concordanceSourceDisplayParametersGroupBox)
        self.concordanceSourceBackgroundColorPushButton.setObjectName(_fromUtf8("concordanceSourceBackgroundColorPushButton"))
        self.gridLayout.addWidget(self.concordanceSourceBackgroundColorPushButton, 1, 3, 1, 1)
        self.concordanceSourceWordsAfterSpinBox.raise_()
        self.concordanceSourceWordsBeforeSpinBox.raise_()
        self.concordanceSourceWordsBeforeLabel.raise_()
        self.concordanceSourceWordsAfterLabel.raise_()
        self.concordanceSourceWordsAfterSpinBox.raise_()
        self.concordanceSourceWordsBeforeSpinBox.raise_()
        self.concordanceSourceWordsBeforeLabel.raise_()
        self.concordanceSourceWordsAfterLabel.raise_()
        self.concordanceSourceFontColorLabel.raise_()
        self.concordanceSourceBackgroundColorLabel.raise_()
        self.concordanceSourceFontColorPushButton.raise_()
        self.concordanceSourceBackgroundColorPushButton.raise_()
        self.gridLayout_2.addWidget(self.concordanceSourceDisplayParametersGroupBox, 3, 0, 1, 2)
        self.concordanceSourceSearchTypesGroupBox = QtGui.QGroupBox(self.concordanceSourceGroupBox)
        self.concordanceSourceSearchTypesGroupBox.setObjectName(_fromUtf8("concordanceSourceSearchTypesGroupBox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.concordanceSourceSearchTypesGroupBox)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.concordanceSourceBasicSearchTypeCheckBox = QtGui.QCheckBox(self.concordanceSourceSearchTypesGroupBox)
        self.concordanceSourceBasicSearchTypeCheckBox.setChecked(True)
        self.concordanceSourceBasicSearchTypeCheckBox.setObjectName(_fromUtf8("concordanceSourceBasicSearchTypeCheckBox"))
        self.horizontalLayout_2.addWidget(self.concordanceSourceBasicSearchTypeCheckBox)
        self.concordanceSourceLemmeSearchTypeCheckBox = QtGui.QCheckBox(self.concordanceSourceSearchTypesGroupBox)
        self.concordanceSourceLemmeSearchTypeCheckBox.setChecked(True)
        self.concordanceSourceLemmeSearchTypeCheckBox.setObjectName(_fromUtf8("concordanceSourceLemmeSearchTypeCheckBox"))
        self.horizontalLayout_2.addWidget(self.concordanceSourceLemmeSearchTypeCheckBox)
        self.concordanceSourceRootSearchTypeCheckBox = QtGui.QCheckBox(self.concordanceSourceSearchTypesGroupBox)
        self.concordanceSourceRootSearchTypeCheckBox.setChecked(True)
        self.concordanceSourceRootSearchTypeCheckBox.setObjectName(_fromUtf8("concordanceSourceRootSearchTypeCheckBox"))
        self.horizontalLayout_2.addWidget(self.concordanceSourceRootSearchTypeCheckBox)
        self.concordanceStrictSearchCheckBox = QtGui.QCheckBox(self.concordanceSourceSearchTypesGroupBox)
        self.concordanceStrictSearchCheckBox.setObjectName(_fromUtf8("concordanceStrictSearchCheckBox"))
        self.horizontalLayout_2.addWidget(self.concordanceStrictSearchCheckBox)
        self.gridLayout_2.addWidget(self.concordanceSourceSearchTypesGroupBox, 2, 0, 1, 2)
        self.verticalLayout_2.addWidget(self.concordanceSourceGroupBox)
        self.concordanceSearchPushButton = QtGui.QPushButton(ConcordanceTab)
        self.concordanceSearchPushButton.setEnabled(False)
        self.concordanceSearchPushButton.setDefault(True)
        self.concordanceSearchPushButton.setObjectName(_fromUtf8("concordanceSearchPushButton"))
        self.verticalLayout_2.addWidget(self.concordanceSearchPushButton)
        self.concordanceResultsGroupBox = QtGui.QGroupBox(ConcordanceTab)
        self.concordanceResultsGroupBox.setObjectName(_fromUtf8("concordanceResultsGroupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.concordanceResultsGroupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.concordanceResultsTextEdit = QtGui.QTextEdit(self.concordanceResultsGroupBox)
        self.concordanceResultsTextEdit.setReadOnly(True)
        self.concordanceResultsTextEdit.setObjectName(_fromUtf8("concordanceResultsTextEdit"))
        self.verticalLayout.addWidget(self.concordanceResultsTextEdit)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.concordanceResultsSavePushButton = QtGui.QPushButton(self.concordanceResultsGroupBox)
        self.concordanceResultsSavePushButton.setObjectName(_fromUtf8("concordanceResultsSavePushButton"))
        self.horizontalLayout.addWidget(self.concordanceResultsSavePushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.concordanceResultsGroupBox)

        self.retranslateUi(ConcordanceTab)
        QtCore.QMetaObject.connectSlotsByName(ConcordanceTab)

    def retranslateUi(self, ConcordanceTab):
        ConcordanceTab.setWindowTitle(_translate("ConcordanceTab", "Concordanceur", None))
        self.concordanceSourceGroupBox.setTitle(_translate("ConcordanceTab", "Recherche d\'un mot", None))
        self.concordanceSourceSelectPushButton.setText(_translate("ConcordanceTab", "Sélectionner", None))
        self.concordanceSourceLineEdit.setPlaceholderText(_translate("ConcordanceTab", "Votre mot", None))
        self.concordanceSourceDisplayParametersGroupBox.setTitle(_translate("ConcordanceTab", "Paramètres d\'affichage", None))
        self.concordanceSourceWordsAfterLabel.setText(_translate("ConcordanceTab", "Nombre de mots après", None))
        self.concordanceSourceWordsBeforeLabel.setText(_translate("ConcordanceTab", "Nombre de mots avant", None))
        self.concordanceSourceFontColorLabel.setText(_translate("ConcordanceTab", "Couleur du texte", None))
        self.concordanceSourceBackgroundColorLabel.setText(_translate("ConcordanceTab", "Couleur du marquage", None))
        self.concordanceSourceFontColorPushButton.setText(_translate("ConcordanceTab", "Sélectionner", None))
        self.concordanceSourceBackgroundColorPushButton.setText(_translate("ConcordanceTab", "Sélectionner", None))
        self.concordanceSourceSearchTypesGroupBox.setTitle(_translate("ConcordanceTab", "Types de recherche", None))
        self.concordanceSourceBasicSearchTypeCheckBox.setText(_translate("ConcordanceTab", "Basique", None))
        self.concordanceSourceLemmeSearchTypeCheckBox.setText(_translate("ConcordanceTab", "Basée lemme", None))
        self.concordanceSourceRootSearchTypeCheckBox.setText(_translate("ConcordanceTab", "Basée racine", None))
        self.concordanceStrictSearchCheckBox.setText(_translate("ConcordanceTab", "Stricte", None))
        self.concordanceSearchPushButton.setText(_translate("ConcordanceTab", "Rechercher", None))
        self.concordanceResultsGroupBox.setTitle(_translate("ConcordanceTab", "Résultats", None))
        self.concordanceResultsSavePushButton.setText(_translate("ConcordanceTab", "Enregistrer", None))

